### ISSUE TITLE
Not working, get errors when compiling

### ISSUE THREAD

**Issue by datee** [jcward/hxtelemetry#46]
CppHxTelemetry.cpp(233): error C2561: 'hxtelemetry::CppHxTelemetry_obj::dump_telemetry_frame': function must return a value

v0.3.4 with hxcpp 3.3.49, haxe 3.2.1 and openfl 4.4.0

Also tried downgrading to 0.3.3/0.3.2.. and it did not solve the issue...

**Comment by zeeshahmad** [comment]
I got a very similar error, and I have managed to fix it by changing line 93 to an if/else clause rather than a return statement: 
[in this file](https://github.com/jcward/hxtelemetry/blob/master/hxtelemetry/CppHxTelemetry.hx#L93)
(Don't forget to end the else statement block with '}'. I only did this in my local version of hxtelemetry I don't know how I can contribute this change (not very competent with git)

**Comment by jcward** [comment]
Alright, this should be fixed. As the commit message notes, there was a `return null()` that was removed at one point. Since that could be a Windows thing, I went with @zeeshahmad's method of an if-clause.

@datee - let me know if it works for you.

**Comment by datee** [comment]
Hm no.. it is still not working....
I'm still getting errors.. although different ones now:

C:/HaxeToolkit/haxe/lib/hxcpp/3,3,49/src/hx/Debug.cpp(373): error C2664: 'uintptr_t _beginthreadex(void *,unsigned int,_beginthreadex_proc_type,void *,unsigned int,unsigned int *)': cannot convert argument 3 from 'DWORD (__stdcall *)(void *)' to '_beginthreadex_proc_type'
C:/HaxeToolkit/haxe/lib/hxcpp/3,3,49/src/hx/Debug.cpp(373): note: None of the functions with this name in scope match the target type

**Comment by jcward** [comment]
Ah, yes, that's an entirely different error message than the one I think is fixed (that is, the return value of `CppHxTelemetry_obj::dump_telemetry_frame`)

That's related to code in a WINDOWS ifdef. Hmm... Alright, I think there was something broken in hxcpp 3.3.49 that I fixed on hxcpp git ([discussion](https://github.com/jcward/hxtelemetry/issues/42#issuecomment-230078049)), but sadly, git has now moved too far to be useful.

Try this hotfix to 3.3.49: in C:/HaxeToolkit/haxe/lib/hxcpp/3,3,49/src/hx/Debug.cpp, near line 372, replace:

```
        if (gThreadRefCount == 1) {
#if defined(HX_WINDOWS)
            _beginthreadex(0, 0, ProfileMainLoop, 0, 0, 0);
#else
            pthread_t result;
            pthread_create(&result, 0, ProfileMainLoop, 0);
#endif
}
```

With:

```
        if (gThreadRefCount == 1) {
            HxCreateDetachedThread(ProfileMainLoop, 0);
        }
```
